### ISSUE TITLE
Update to Unicode 11.0

### ISSUE THREAD

**Issue by eyeplum** [open-i18n/rust-unic#259]
### Description

Update external data and all modules to Unicode 11.0. For changes in Unicode 11.0, see: https://www.unicode.org/versions/Unicode11.0.0/

### Tasks

These tasks are roughly planned out according to changes in Unicode 11.0 and the potential impact of `rust-unic`'s implementation.

#### UCD

- [ ] Implement new grapheme cluster breaking rules
  - [ ] Implement the new `Extended_Pictographic` property
  - [ ] Remove GB10 implementation
  - [ ] Implement the new GB11 rule
- [ ] Implement new word breaking rules
- [ ] [Optional] Implement the new `Equivalent_Unified_Ideograph` property

#### Emoji

- [ ] Add `.rsv` table for the new `Extended_Pictographic` property (other works are captured by UCD)

#### IDNA

- [ ] Update IDNA conformance test to the new format

### Related Issues, Pull Requests, Forks

- https://github.com/open-i18n/rust-unic/issues/219
- https://github.com/open-i18n/rust-unic/pull/226
- https://github.com/eyeplum/rust-unic/commit/6e88739187371794b72db8b6651b955269accd98

**Comment by behnam** [comment]
https://github.com/unicode-rs/unicode-segmentation/issues/43 is tracking segmentation algorithm updates. I think we can keep the code in sync with `unicode-segmentation`, regardless of where we do the impl first.
